"""initial schema

Revision ID: 483200f012b7
Revises: 
Create Date: 2026-06-25 15:05:55.313245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483200f012b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('breach_count', sa.Integer(), nullable=False),
    sa.Column('services_total', sa.Integer(), nullable=False),
    sa.Column('services_down_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_runs_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('trigger', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.String(length=40), nullable=True),
    sa.Column('preview_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)

    op.create_table('instances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['instance_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=True),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('instance_id', sa.String(length=64), nullable=True),
    sa.Column('instance_name', sa.String(length=120), nullable=True),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('namespace', sa.String(length=120), nullable=True),
    sa.Column('metric_name', sa.String(length=120), nullable=True),
    sa.Column('stat', sa.String(length=40), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('comparison', sa.String(length=4), nullable=True),
    sa.Column('agent_required', sa.Boolean(), nullable=True),
    sa.Column('breached', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_results_scan_run_id'), ['scan_run_id'], unique=False)

    op.create_table('service_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=True),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('instance_id', sa.String(length=64), nullable=True),
    sa.Column('instance_name', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('svc_type', sa.String(length=10), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('up', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_results_scan_run_id'), ['scan_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_results_scan_run_id'))

    op.drop_table('service_results')
    with op.batch_alter_table('metric_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_results_scan_run_id'))

    op.drop_table('metric_results')
    op.drop_table('instances')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_runs_created_at'))

    op.drop_table('scan_runs')
    op.drop_table('instance_groups')
    # ### end Alembic commands ###
